In [85]:
import pandas as pd
import numpy as np

In [89]:
df=pd.read_csv("Today's Price - 2026-09-16.csv", on_bad_lines="warn")

C:\Users\JAY\AppData\Local\Temp\ipykernel_12520\278019110.py:1: ParserWarning: Skipping line 200: expected 19 fields, saw 20
Skipping line 351: expected 19 fields, saw 20

  df=pd.read_csv("Today's Price - 2026-09-16.csv", on_bad_lines="warn")

In [16]:
df.head()

,Id,Business Date,Security Id,Symbol,Security Name,Open Price,High Price,Low Price,Close Price,Total Traded Quantity,Total Traded Value,Previous Day Close Price,Fifty Two Week High,Fifty Two Week Low,Last Updated Time,Last Updated Price,Total Trades,Average Traded Price,Market Capitalization
0,1,2026-09-16,131,NABIL,Nabil Bank Limited,565.0,567.0,557.2,560.0,55113,30903609.0,560.0,581.0,471.0,2026-09-16T14:59:27.707475,560.0,504,560.73,151519.19
1,2,2026-09-16,132,NIMB,Nepal Investment Mega Bank Limited,193.0,193.0,190.1,192.0,93883,18007034.8,192.0,232.5,181.0,2026-09-16T14:59:48.648563,192.0,290,191.80,65526.90
2,3,2026-09-16,133,SCB,Standard Chartered Bank Limited,655.0,657.0,650.1,650.1,6942,4528053.4,653.0,712.6,594.9,2026-09-16T14:58:24.861974,650.1,68,652.26,65285.44
3,4,2026-09-16,134,HBL,Himalayan Bank Limited,190.0,199.8,190.0,193.9,70051,13703424.0,195.1,237.0,183.0,2026-09-16T14:59:58.904075,193.9,484,195.62,43785.84
4,5,2026-09-16,135,SBI,Nepal SBI Bank Limited,411.0,411.0,401.1,406.0,3336,1353410.5,409.9,441.0,363.0,2026-09-16T14:59:57.524026,406.0,35,405.69,46020.61

In [17]:
df.shape

(348, 19)

In [18]:
df.isna().sum()

Id                          0
Business Date               0
Security Id                 0
Symbol                      0
Security Name               0
Open Price                  0
High Price                  0
Low Price                   0
Close Price                 0
Total Traded Quantity       0
Total Traded Value          0
Previous Day Close Price    0
Fifty Two Week High         0
Fifty Two Week Low          0
Last Updated Time           0
Last Updated Price          0
Total Trades                0
Average Traded Price        0
Market Capitalization       1
dtype: int64

In [19]:
df[df['Market Capitalization'].isna()]

,Id,Business Date,Security Id,Symbol,Security Name,Open Price,High Price,Low Price,Close Price,Total Traded Quantity,Total Traded Value,Previous Day Close Price,Fifty Two Week High,Fifty Two Week Low,Last Updated Time,Last Updated Price,Total Trades,Average Traded Price,Market Capitalization
330,332,2026-09-16,9327,ICFCD89,8% ICFC Finance Limited Debenture 2089,1081.8,1095.0,1081.8,1095.0,105,114520.0,1095.0,1140.0,1020.0,2026-09-16T14:59:34.59418,1095.0,5,1090.66,NaN

Market Capitalization isn't relevant field to our analysis.So lets ignore it.

In [24]:
scripts=df['Symbol']
scripts

0      NABIL
1       NIMB
2        SCB
3        HBL
4        SBI
       ...
343    SAEF2
344    LSH12
345     RSY2
346    MEPDL
347    SAPIL
Name: Symbol, Length: 348, dtype: str

In [26]:
(df['Close Price'].dtype)

dtype('float64')

Assuming that mutual fund unit prices are below 20.This assumption is not always true, but it works for our current analysis.

In [ ]:
mutual_f=df[df['Close Price']<20]

In [30]:
mutual_f

,Id,Business Date,Security Id,Symbol,Security Name,Open Price,High Price,Low Price,Close Price,Total Traded Quantity,Total Traded Value,Previous Day Close Price,Fifty Two Week High,Fifty Two Week Low,Last Updated Time,Last Updated Price,Total Trades,Average Traded Price,Market Capitalization
122,123,2026-09-16,2770,SEF,Siddhartha Equity Fund,9.50,9.60,9.50,9.57,61300,587394.40,9.78,11.53,8.60,2026-09-16T14:59:58.009197,9.57,16,9.58,1435.50
146,147,2026-09-16,2835,NBF2,NABIL BALANCED FUND-2,9.83,9.83,9.55,9.55,1100,10561.00,9.83,10.70,8.89,2026-09-16T14:32:46.896944,9.55,3,9.60,1069.60
149,150,2026-09-16,2859,SIGS2,Siddhartha Investment Growth Scheme - 2,9.82,9.82,9.60,9.60,11185,107632.70,9.54,11.50,8.90,2026-09-16T14:24:18.412999,9.60,3,9.62,1152.00
151,152,2026-09-16,2863,NICBF,NIC Asia Balanced Fund,8.90,9.16,8.90,8.91,600,5370.00,8.95,11.20,8.45,2026-09-16T14:36:41.114646,8.91,3,8.95,672.71
162,163,2026-09-16,2902,LUK,Laxmi Unnati Kosh,9.31,9.34,9.31,9.34,200,1865.00,9.50,10.91,8.97,2026-09-16T12:53:22.118955,9.34,2,9.32,609.55
171,172,2026-09-16,2923,SLCF,Sanima Large Cap Fund,9.20,9.48,9.20,9.48,4900,46378.00,9.20,10.70,8.60,2026-09-16T14:58:00.756534,9.48,4,9.46,1137.60
175,176,2026-09-16,2933,KEF,Kumari Equity Fund,9.22,9.57,9.22,9.50,2440,23012.80,9.50,11.30,8.31,2026-09-16T14:36:35.375635,9.50,9,9.43,950.00
178,179,2026-09-16,2937,SBCF,Sunrise Bluechip Fund,9.30,9.40,9.03,9.03,30800,281815.00,9.33,11.16,8.73,2026-09-16T14:48:29.576893,9.03,7,9.14,1128.75
180,181,2026-09-16,4947,PSF,Prabhu Select Fund,10.85,11.00,10.85,10.91,18050,197894.00,11.16,13.00,9.91,2026-09-16T14:42:33.740634,10.91,12,10.96,1363.75
182,183,2026-09-16,4949,NIBSF2,NIBL Samriddhi Fund -2,8.80,8.84,8.62,8.62,27310,236834.40,8.66,11.13,8.10,2026-09-16T14:46:36.874742,8.62,11,8.67,1293.00
184,185,2026-09-16,4967,NICSF,NIC Asia Select Fund 30,8.50,8.50,8.50,8.50,7245,61582.50,8.50,9.97,8.04,2026-09-16T14:58:25.831298,8.50,10,8.50,1062.50
185,186,2026-09-16,4968,RMF1,RBB Mutual Fund 1,9.46,9.50,9.46,9.46,21675,205500.50,9.45,11.02,8.65,2026-09-16T14:19:57.582772,9.46,13,9.48,1182.50
192,193,2026-09-16,8023,MMF1,Mega Mutual Fund -1,8.63,8.98,8.63,8.97,4169,36694.62,8.89,10.16,8.22,2026-09-16T14:51:07.465665,8.97,17,8.80,1121.25
193,194,2026-09-16,8024,NBF3,Nabil Balanced Fund-3,9.05,9.50,9.05,9.41,6886,63930.00,9.23,10.22,8.35,2026-09-16T14:57:27.635014,9.41,15,9.28,1176.25
207,209,2026-09-16,8073,NICFC,NIC Asia Flexi CAP Fund,8.70,8.96,8.70,8.96,5905,52323.80,8.71,9.89,8.37,2026-09-16T14:59:49.397369,8.96,17,8.86,91.39
208,210,2026-09-16,8074,KDBY,Kumari Dhanabriddhi Yojana,9.99,10.20,9.99,10.15,32900,331605.00,10.19,12.54,8.67,2026-09-16T14:58:50.111491,10.15,25,10.07,40.60
217,219,2026-09-16,8106,GIBF1,Global IME Balanced Fund-1,11.65,11.65,11.50,11.50,8200,94720.00,11.60,11.93,9.30,2026-09-16T14:50:54.316397,11.50,11,11.55,1179.63
224,226,2026-09-16,8125,NSIF2,NMB Sulav Investment Fund - 2,9.95,10.00,9.95,10.00,300,2995.00,9.95,11.45,9.65,2026-09-16T14:05:33.791213,10.00,3,9.98,1221.00
230,232,2026-09-16,9138,NIBLGF,NIBL Growth Fund,8.60,8.60,8.40,8.48,406450,3445196.50,8.60,11.81,8.10,2026-09-16T14:33:22.280338,8.48,14,8.47,1119.36
231,233,2026-09-16,9139,SAGF,Sanima Growth Fund,9.38,9.50,9.38,9.40,1450,13673.00,9.38,11.31,8.79,2026-09-16T14:47:35.698323,9.40,5,9.42,632.18
239,241,2026-09-16,9154,SFEF,Sunrise Focused Equity Fund,9.12,9.20,9.00,9.20,24515,225455.00,9.40,10.65,8.89,2026-09-16T14:44:10.734056,9.20,12,9.19,920.00
249,251,2026-09-16,9174,PRSF,Prabhu Smart Fund,11.97,11.98,11.82,11.82,92600,1102489.00,11.94,13.61,9.85,2026-09-16T14:59:48.532806,11.82,21,11.90,1182.00
252,254,2026-09-16,9178,RMF2,RBB Mutual Fund 2,9.56,9.76,9.56,9.76,300,2907.00,9.76,10.71,8.82,2026-09-16T14:42:19.079686,9.76,3,9.69,825.81
255,257,2026-09-16,9182,SIGS3,Siddhartha Investment Growth Scheme 3,10.36,10.36,10.36,10.36,860,8909.60,10.38,11.58,8.50,2026-09-16T11:49:25.076008,10.36,1,10.36,834.81
258,260,2026-09-16,9191,C30MF,Citizens Super 30 Mutual Fund,9.96,9.96,9.96,9.96,100,996.00,10.15,10.45,8.70,2026-09-16T13:26:58.956386,9.96,1,9.96,747.72
263,265,2026-09-16,9198,LVF2,Laxmi Value Fund 2,9.06,9.33,9.06,9.33,5500,51018.00,9.34,10.30,8.76,2026-09-16T14:35:39.47112,9.33,11,9.27,746.40
277,279,2026-09-16,9221,H8020,Himalayan 80-20,12.43,12.48,12.20,12.40,183008,2259938.83,12.33,13.18,10.00,2026-09-16T14:59:09.302055,12.40,24,12.34,124.00
283,285,2026-09-16,9236,NICGF2,NIC ASIA Growth Fund-2,8.51,8.56,8.51,8.54,18020,153905.40,8.55,10.13,8.33,2026-09-16T13:45:36.233188,8.54,14,8.54,772.87
285,287,2026-09-16,9241,KSY,Kumari Sabal Yojana,8.81,8.84,8.81,8.84,400,3527.00,8.85,10.26,8.21,2026-09-16T13:44:38.7921,8.84,3,8.81,658.36
288,290,2026-09-16,9244,NIBLSTF,NIBL Stable Fund,8.32,8.50,8.15,8.30,208732,1715563.30,8.36,10.85,8.00,2026-09-16T14:49:23.594252,8.30,16,8.21,937.90
289,291,2026-09-16,9245,MNMF1,Muktinath Mutual Fund 1,9.10,9.30,9.10,9.18,8650,80066.50,9.11,10.40,8.53,2026-09-16T14:34:26.727884,9.18,10,9.25,1147.50
291,293,2026-09-16,9248,GSY,Garima Samriddhi Yojana,8.90,9.15,8.90,9.15,1100,9888.00,9.15,10.46,8.50,2026-09-16T14:43:12.413027,9.15,11,8.98,1143.75
295,297,2026-09-16,9254,NMBHF2,NMB Hybrid Fund L- II,9.00,9.00,8.47,8.47,285500,2480120.00,9.18,10.20,8.36,2026-09-16T14:56:07.562887,8.47,18,8.68,1156.02
298,300,2026-09-16,9257,MBLEF,MBL Equity Fund,9.11,9.25,9.11,9.25,6200,57322.00,9.32,10.89,8.44,2026-09-16T14:12:40.2122,9.25,10,9.24,1125.03
300,302,2026-09-16,9259,RSY,Reliable Samriddhi Yojana,9.30,9.39,9.30,9.39,7820,73351.80,9.30,10.70,8.71,2026-09-16T14:40:23.736381,9.39,9,9.38,1126.80
305,307,2026-09-16,9269,GBIMESY2,Global IME Sammunat Yojana -2,8.85,8.86,8.85,8.86,200,1771.00,8.85,10.78,8.50,2026-09-16T14:45:10.827927,8.86,2,8.85,1329.00
310,312,2026-09-16,9290,HLICF,HLI Large Cap Fund,8.24,8.26,8.24,8.26,700,5773.00,8.26,10.55,7.88,2026-09-16T13:37:18.388205,8.26,7,8.24,4130.00
318,320,2026-09-16,9302,RBBF40,RBB Focus 40,9.20,9.20,8.76,9.02,900,8083.00,9.11,10.36,8.73,2026-09-16T14:23:36.99838,9.02,9,8.98,1127.50
320,322,2026-09-16,9304,CSY,Citizens Santulit Yojana,8.32,8.59,8.32,8.35,6190,52670.70,8.35,10.00,8.01,2026-09-16T14:44:35.375707,8.35,16,8.50,1043.75
325,327,2026-09-16,9312,NSY,Nepal Life Samriddhi Lagani Yojana,9.12,9.40,9.12,9.12,12600,115037.00,9.40,10.19,8.85,2026-09-16T14:54:51.325582,9.12,17,9.12,1824.00
342,344,2026-09-16,9348,SEF2,Siddhartha Equity Fund 2,9.05,9.10,8.91,9.06,6000,53963.00,9.10,10.00,8.50,2026-09-16T14:49:21.154929,9.06,41,8.99,1132.50
343,345,2026-09-16,9349,SAEF2,Sanima Equity Fund-2,8.97,9.05,8.97,9.00,3500,31550.00,9.05,10.00,8.76,2026-09-16T14:38:34.693637,9.00,23,9.01,1125.00
344,346,2026-09-16,9350,LSH12,LS Horizon 12,9.00,9.05,9.00,9.04,2500,22589.00,9.00,10.00,8.55,2026-09-16T14:38:12.803834,9.04,15,9.03,1356.00
345,347,2026-09-16,9351,RSY2,Reliable Samriddhi Yojana -2,9.10,9.16,8.91,9.05,241553,2185723.65,9.20,10.00,8.42,2026-09-16T14:59:33.231684,9.05,31,9.04,1131.25

In [33]:
len(mutual_f)

44

In [40]:
Remaining = df.drop(mutual_f.index)
Remaining

,Id,Business Date,Security Id,Symbol,Security Name,Open Price,High Price,Low Price,Close Price,Total Traded Quantity,Total Traded Value,Previous Day Close Price,Fifty Two Week High,Fifty Two Week Low,Last Updated Time,Last Updated Price,Total Trades,Average Traded Price,Market Capitalization
0,1,2026-09-16,131,NABIL,Nabil Bank Limited,565.0,567.0,557.2,560.0,55113,30903609.0,560.0,581.0,471.0,2026-09-16T14:59:27.707475,560.0,504,560.73,151519.19
1,2,2026-09-16,132,NIMB,Nepal Investment Mega Bank Limited,193.0,193.0,190.1,192.0,93883,18007034.8,192.0,232.5,181.0,2026-09-16T14:59:48.648563,192.0,290,191.80,65526.90
2,3,2026-09-16,133,SCB,Standard Chartered Bank Limited,655.0,657.0,650.1,650.1,6942,4528053.4,653.0,712.6,594.9,2026-09-16T14:58:24.861974,650.1,68,652.26,65285.44
3,4,2026-09-16,134,HBL,Himalayan Bank Limited,190.0,199.8,190.0,193.9,70051,13703424.0,195.1,237.0,183.0,2026-09-16T14:59:58.904075,193.9,484,195.62,43785.84
4,5,2026-09-16,135,SBI,Nepal SBI Bank Limited,411.0,411.0,401.1,406.0,3336,1353410.5,409.9,441.0,363.0,2026-09-16T14:59:57.524026,406.0,35,405.69,46020.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,341,2026-09-16,9345,SGHL,Sanigad Hydro Limited,499.9,510.0,495.0,497.0,46218,23180933.9,508.3,587.0,299.3,2026-09-16T14:59:58.162579,497.0,1015,501.55,14164.50
340,342,2026-09-16,9346,KAHL,Kalanga Hydro Limited,490.9,509.0,490.9,493.5,22537,11213694.2,506.0,613.0,295.4,2026-09-16T14:59:59.135593,493.5,571,497.56,6909.00
341,343,2026-09-16,9347,ECL,Everest Colour Limited,1375.0,1384.0,1320.0,1343.0,14415,19349063.1,1384.0,1980.0,296.6,2026-09-16T14:59:58.205859,1343.0,264,1342.28,4029.00
346,348,2026-09-16,9352,MEPDL,Mount Everest Power Development Limited,675.0,705.0,666.0,703.0,68537,47329266.8,673.5,855.0,300.0,2026-09-16T14:59:58.911277,703.0,1390,690.56,6045.80
347,349,2026-09-16,9353,SAPIL,Sarvottam Paints Industries Limited,1389.0,1410.0,1365.0,1400.0,21458,29711090.2,1420.0,1604.0,300.0,2026-09-16T14:59:55.237059,1400.0,643,1384.61,4760.00

In [41]:
Remaining.shape[0]

304

Classifying a security as a debenture if its name contains terms such as “bond” or “debenture".

In [42]:
debenture_ = Remaining[Remaining['Security Name'].str.contains('debenture|bond', case=False)]
debenture_

,Id,Business Date,Security Id,Symbol,Security Name,Open Price,High Price,Low Price,Close Price,Total Traded Quantity,Total Traded Value,Previous Day Close Price,Fifty Two Week High,Fifty Two Week Low,Last Updated Time,Last Updated Price,Total Trades,Average Traded Price,Market Capitalization
152,153,2026-09-16,2875,PBLD86,10.25% Prabhu Bank Debenture 2086,1103.00,1103.0,1103.00,1104.1,3,3312.3,1103.0,1470.0,1100.2,2026-09-16T14:29:55.137916,1104.1,1,1104.10,1104.10
153,154,2026-09-16,2878,SRBLD83,10.25% Sunrise Bank Debenture 2083,1020.80,1020.8,1020.60,1020.6,25,25517.0,1020.0,1125.0,1006.1,2026-09-16T14:58:55.383557,1020.6,2,1020.68,3061.80
156,157,2026-09-16,2882,ICFCD83,12% ICFC Finance Limited Debenture 2083,868.40,868.4,868.40,921.2,2,1815.6,868.4,1272.2,843.2,2026-09-16T11:40:29.898968,921.2,2,907.80,184.24
157,158,2026-09-16,2886,ADBLD83,10.35% Agricultural Bank Debenture 2083,1038.50,1038.5,1038.50,1038.5,10,10385.0,1038.0,1132.9,1015.0,2026-09-16T14:58:42.864007,1038.5,1,1038.50,2596.25
159,160,2026-09-16,2889,CIZBD86,10.25% Citizens Bank Debenture 2086,1210.00,1210.0,1210.00,1210.0,22,26620.0,1210.0,1320.9,1112.3,2026-09-16T11:21:30.768645,1210.0,1,1210.00,3025.00
174,175,2026-09-16,2932,MFLD85,9.5% Manjushree Finance Limited Debenture 2085,1100.00,1104.0,1100.00,1104.0,75,82600.0,1096.0,1203.0,1064.0,2026-09-16T14:55:58.898746,1104.0,3,1101.33,552.00
181,182,2026-09-16,4948,KSBBLD87,9% Kamana Sewa Bikas Bank Limited Debenture 2087,1112.20,1112.2,1112.20,1112.2,25,27805.0,1112.2,1229.0,1047.0,2026-09-16T12:07:37.438317,1112.2,1,1112.20,1112.20
186,187,2026-09-16,4969,MND84/85,Muktinath Debenture 2084/85,1068.00,1068.0,1068.00,1068.0,20,21360.0,1037.7,1128.0,1037.7,2026-09-16T11:11:44.551231,1068.0,1,1068.00,1335.00
205,207,2026-09-16,8068,CCBD88,Century Debenture 2088,1210.00,1210.0,1210.00,1210.0,25,30250.0,1210.0,1326.0,1137.0,2026-09-16T14:58:47.877107,1210.0,1,1210.00,2662.00
211,213,2026-09-16,8097,PBD88,10% Prime Debenture 2088,1167.00,1200.0,1155.10,1200.0,163,191895.1,1180.0,1285.0,1131.0,2026-09-16T14:58:27.644569,1200.0,11,1177.27,2090.26
212,214,2026-09-16,8098,SBLD89,10.75% SBL Debenture 2089,1297.00,1297.0,1297.00,1297.0,50,64850.0,1293.5,1450.0,1190.0,2026-09-16T14:24:49.672101,1297.0,3,1297.00,5188.00
284,286,2026-09-16,9238,NABILD87,9% Nabil Debenture 2087,1101.00,1101.0,1101.00,1101.0,25,27525.0,1101.0,1200.0,1087.5,2026-09-16T12:58:24.347363,1101.0,1,1101.00,3303.00
287,289,2026-09-16,9243,NIMBD90,10% NIMB Debenture 2090,1176.50,1176.5,1176.50,1176.5,25,29412.5,1200.1,1425.0,1140.0,2026-09-16T13:11:53.761262,1176.5,1,1176.50,4753.06
292,294,2026-09-16,9249,ICFCD88,9% ICFC Finance Limited Debenture 2088,1121.00,1121.0,1121.00,1121.0,25,28025.0,1118.0,1216.0,1080.0,2026-09-16T13:55:48.221853,1121.0,1,1121.00,336.30
296,298,2026-09-16,9255,EBLD91,Everest Bank Limited Debenture 2091,1085.00,1110.0,1085.00,1110.0,150,165270.0,1090.0,1142.4,995.0,2026-09-16T14:35:38.589513,1110.0,3,1101.80,3330.00
301,303,2026-09-16,9261,NIFRAGED,Nifra Green Energy Debenture 6% - 2088/89,1025.00,1025.4,1025.00,1025.4,50,51260.0,1025.2,1200.2,986.0,2026-09-16T14:22:03.692757,1025.4,2,1025.20,5127.00
307,309,2026-09-16,9271,SBLD2091,7.25% SBL Debenture 2091,1194.69,1206.0,1194.69,1206.0,8838,10656392.0,1194.8,1194.8,109.0,2026-09-16T11:02:53.182115,1206.0,5,1205.74,3015.00
308,310,2026-09-16,9286,SHINED,Shine Resunga Debenture,1101.00,1101.0,1101.00,1101.0,50,55050.0,1096.0,1200.0,1000.0,2026-09-16T14:59:39.014076,1101.0,1,1101.00,1101.00
330,332,2026-09-16,9327,ICFCD89,8% ICFC Finance Limited Debenture 2089,1081.80,1095.0,1081.80,1095.0,105,114520.0,1095.0,1140.0,1020.0,2026-09-16T14:59:34.59418,1095.0,5,1090.66,NaN

In [44]:
debenture_.shape

(19, 19)

In [50]:
ordinary_S= Remaining[~Remaining['Security Name'].str.contains('debenture|bond', case=False)]
ordinary_S

,Id,Business Date,Security Id,Symbol,Security Name,Open Price,High Price,Low Price,Close Price,Total Traded Quantity,Total Traded Value,Previous Day Close Price,Fifty Two Week High,Fifty Two Week Low,Last Updated Time,Last Updated Price,Total Trades,Average Traded Price,Market Capitalization
0,1,2026-09-16,131,NABIL,Nabil Bank Limited,565.0,567.0,557.2,560.0,55113,30903609.0,560.0,581.0,471.0,2026-09-16T14:59:27.707475,560.0,504,560.73,151519.19
1,2,2026-09-16,132,NIMB,Nepal Investment Mega Bank Limited,193.0,193.0,190.1,192.0,93883,18007034.8,192.0,232.5,181.0,2026-09-16T14:59:48.648563,192.0,290,191.80,65526.90
2,3,2026-09-16,133,SCB,Standard Chartered Bank Limited,655.0,657.0,650.1,650.1,6942,4528053.4,653.0,712.6,594.9,2026-09-16T14:58:24.861974,650.1,68,652.26,65285.44
3,4,2026-09-16,134,HBL,Himalayan Bank Limited,190.0,199.8,190.0,193.9,70051,13703424.0,195.1,237.0,183.0,2026-09-16T14:59:58.904075,193.9,484,195.62,43785.84
4,5,2026-09-16,135,SBI,Nepal SBI Bank Limited,411.0,411.0,401.1,406.0,3336,1353410.5,409.9,441.0,363.0,2026-09-16T14:59:57.524026,406.0,35,405.69,46020.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,341,2026-09-16,9345,SGHL,Sanigad Hydro Limited,499.9,510.0,495.0,497.0,46218,23180933.9,508.3,587.0,299.3,2026-09-16T14:59:58.162579,497.0,1015,501.55,14164.50
340,342,2026-09-16,9346,KAHL,Kalanga Hydro Limited,490.9,509.0,490.9,493.5,22537,11213694.2,506.0,613.0,295.4,2026-09-16T14:59:59.135593,493.5,571,497.56,6909.00
341,343,2026-09-16,9347,ECL,Everest Colour Limited,1375.0,1384.0,1320.0,1343.0,14415,19349063.1,1384.0,1980.0,296.6,2026-09-16T14:59:58.205859,1343.0,264,1342.28,4029.00
346,348,2026-09-16,9352,MEPDL,Mount Everest Power Development Limited,675.0,705.0,666.0,703.0,68537,47329266.8,673.5,855.0,300.0,2026-09-16T14:59:58.911277,703.0,1390,690.56,6045.80
347,349,2026-09-16,9353,SAPIL,Sarvottam Paints Industries Limited,1389.0,1410.0,1365.0,1400.0,21458,29711090.2,1420.0,1604.0,300.0,2026-09-16T14:59:55.237059,1400.0,643,1384.61,4760.00

In [51]:
ordinary_S.shape

(285, 19)

Soaltee is a special case among ordinary shares, requiring a minimum purchase of 100 units.

In [54]:
shl_=ordinary_S[ordinary_S['Security Name'].str.contains('Soaltee ', case=False)]
shl_

,Id,Business Date,Security Id,Symbol,Security Name,Open Price,High Price,Low Price,Close Price,Total Traded Quantity,Total Traded Value,Previous Day Close Price,Fifty Two Week High,Fifty Two Week Low,Last Updated Time,Last Updated Price,Total Trades,Average Traded Price,Market Capitalization
11,12,2026-09-16,147,SHL,Soaltee Hotel Limited,509.0,510.0,501.0,508.1,20290,10279179.0,509.9,559.8,464.0,2026-09-16T14:56:21.874119,508.1,68,506.61,59709.5

In [56]:
net_ordinary_S=ordinary_S[~ordinary_S['Security Name'].str.contains('Soaltee ', case=False)]
net_ordinary_S

,Id,Business Date,Security Id,Symbol,Security Name,Open Price,High Price,Low Price,Close Price,Total Traded Quantity,Total Traded Value,Previous Day Close Price,Fifty Two Week High,Fifty Two Week Low,Last Updated Time,Last Updated Price,Total Trades,Average Traded Price,Market Capitalization
0,1,2026-09-16,131,NABIL,Nabil Bank Limited,565.0,567.0,557.2,560.0,55113,30903609.0,560.0,581.0,471.0,2026-09-16T14:59:27.707475,560.0,504,560.73,151519.19
1,2,2026-09-16,132,NIMB,Nepal Investment Mega Bank Limited,193.0,193.0,190.1,192.0,93883,18007034.8,192.0,232.5,181.0,2026-09-16T14:59:48.648563,192.0,290,191.80,65526.90
2,3,2026-09-16,133,SCB,Standard Chartered Bank Limited,655.0,657.0,650.1,650.1,6942,4528053.4,653.0,712.6,594.9,2026-09-16T14:58:24.861974,650.1,68,652.26,65285.44
3,4,2026-09-16,134,HBL,Himalayan Bank Limited,190.0,199.8,190.0,193.9,70051,13703424.0,195.1,237.0,183.0,2026-09-16T14:59:58.904075,193.9,484,195.62,43785.84
4,5,2026-09-16,135,SBI,Nepal SBI Bank Limited,411.0,411.0,401.1,406.0,3336,1353410.5,409.9,441.0,363.0,2026-09-16T14:59:57.524026,406.0,35,405.69,46020.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,341,2026-09-16,9345,SGHL,Sanigad Hydro Limited,499.9,510.0,495.0,497.0,46218,23180933.9,508.3,587.0,299.3,2026-09-16T14:59:58.162579,497.0,1015,501.55,14164.50
340,342,2026-09-16,9346,KAHL,Kalanga Hydro Limited,490.9,509.0,490.9,493.5,22537,11213694.2,506.0,613.0,295.4,2026-09-16T14:59:59.135593,493.5,571,497.56,6909.00
341,343,2026-09-16,9347,ECL,Everest Colour Limited,1375.0,1384.0,1320.0,1343.0,14415,19349063.1,1384.0,1980.0,296.6,2026-09-16T14:59:58.205859,1343.0,264,1342.28,4029.00
346,348,2026-09-16,9352,MEPDL,Mount Everest Power Development Limited,675.0,705.0,666.0,703.0,68537,47329266.8,673.5,855.0,300.0,2026-09-16T14:59:58.911277,703.0,1390,690.56,6045.80
347,349,2026-09-16,9353,SAPIL,Sarvottam Paints Industries Limited,1389.0,1410.0,1365.0,1400.0,21458,29711090.2,1420.0,1604.0,300.0,2026-09-16T14:59:55.237059,1400.0,643,1384.61,4760.00

In [65]:
mutual_=mutual_f[['Symbol','Close Price']]
mutual_

       Symbol  Close Price
122       SEF         9.57
146      NBF2         9.55
149     SIGS2         9.60
151     NICBF         8.91
162       LUK         9.34
171      SLCF         9.48
175       KEF         9.50
178      SBCF         9.03
180       PSF        10.91
182    NIBSF2         8.62
184     NICSF         8.50
185      RMF1         9.46
192      MMF1         8.97
193      NBF3         9.41
207     NICFC         8.96
208      KDBY        10.15
217     GIBF1        11.50
224     NSIF2        10.00
230    NIBLGF         8.48
231      SAGF         9.40
239      SFEF         9.20
249      PRSF        11.82
252      RMF2         9.76
255     SIGS3        10.36
258     C30MF         9.96
263      LVF2         9.33
277     H8020        12.40
283    NICGF2         8.54
285       KSY         8.84
288   NIBLSTF         8.30
289     MNMF1         9.18
291       GSY         9.15
295    NMBHF2         8.47
298     MBLEF         9.25
300       RSY         9.39
305  GBIMESY2         8.86
310     HLICF         8.26
318    RBBF40         9.02
320       CSY         8.35
325       NSY         9.12
342      SEF2         9.06
343     SAEF2         9.00
344     LSH12         9.04
345      RSY2         9.05

In [83]:
ordinary_=net_ordinary_S[['Symbol','Close Price']]
ordinary_

    Symbol  Close Price
0    NABIL        560.0
1     NIMB        192.0
2      SCB        650.1
3      HBL        193.9
4      SBI        406.0
..     ...          ...
339   SGHL        497.0
340   KAHL        493.5
341    ECL       1343.0
346  MEPDL        703.0
347  SAPIL       1400.0

[284 rows x 2 columns]

Minimum Purchase Requirements
1.Mutual fund: minimum 100 units
2.Ordinary share: minimum 10 units
3.SHL(Special Case): minimum 100 units
4.Debenture: minimum 25 units

In [76]:
def SubCategory(debenture_,mutual_,ordinary_,shl_):
    i,j,k,l = 0,0,0,0
    for index, row in debenture_.iterrows():
        i += row['Close Price'] * 25
    for index, row in mutual_.iterrows():
        j += row['Close Price'] * 100
    for index, row in ordinary_.iterrows():
        k += row['Close Price'] * 10 
    for index, row in shl_.iterrows():
        l += row['Close Price'] * 100 
    
    return i,j,k,l

In [77]:
SubCategory(debenture_,mutual_,ordinary_,shl_)

(530537.5, 41305.0, 2822558.0, 50810.0)

In [79]:
net_total=sum(SubCategory(debenture_,mutual_,ordinary_,shl_))

In [90]:
print(f"So, buddy, would you lend me Rs. {net_total:,} to own the whole NEPSE?🙃")

So, buddy, would you lend me Rs. 3,445,210.5 to own the whole NEPSE?🙃